# -*- coding: utf-8 -*-
"""Practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ieNzzNOjlO3DNIzHnmv6GTSatPZbjhpL
"""



import numpy as np
import matplotlib.pyplot as plt
import matplotlib.mlab as mlab

np.random.seed(19680801)

n = 100000
x = np.random.standard_normal(n)
y = 2.0 + 3.0 * x + 4.0 * np.random.standard_normal(n)
xmin = x.min()
xmax = x.max()
ymin = y.min()
ymax = y.max()

fig, axs = plt.subplots(ncols=2, sharey=True, figsize=(7, 4))
fig.subplots_adjust(hspace=0.5, left=0.07, right=0.93)
ax = axs[0]
hb = ax.hexbin(x, y, gridsize=50, cmap='inferno')
ax.axis([xmin, xmax, ymin, ymax])
ax.set_title("Hexagon binning")
cb = fig.colorbar(hb, ax=ax)
cb.set_label('counts')

ax = axs[1]
hb = ax.hexbin(x, y, gridsize=50, bins='log', cmap='inferno')
ax.axis([xmin, xmax, ymin, ymax])
ax.set_title("With a log color scale")
cb = fig.colorbar(hb, ax=ax)
cb.set_label('log10(N)')

plt.show()

import numpy as np
import matplotlib.pyplot as plt
np.random.seed(8)
x = np.random.normal(0,1,1000000)
y = 3*x + 5*np.random.normal(0,1,1000000)
fig , ax = plt.subplots()
ax.hexbin(x = x , y = y,bins = "log")
plt.show()

import numpy as np
import matplotlib.pyplot as plt
x,y=np.meshgrid(np.linspace(-5,10,100),np.linspace(-5,10,100))
z = np.sqrt(x**2 + y**2)
fig, ax = plt.subplots()
ax.contourf(x,y,z)

import numpy as np
import matplotlib.pyplot as plt
np.random.seed(4072023)
x = np.random.normal(size=200)
y = np.random.normal(size=200)
z = np.random.normal(size=200)
fig = plt.figure()
ax = fig.add_subplot(projection='3d')
ax.scatter(x,y,z)
ax.set_xlabel('X-axis label')
ax.set_ylabel('Y-axis label')
ax.set_zlabel('Z-axis label')
plt.title("3D scatter plot")
ax.scatter(x,y,z,cmap="viridis")

import numpy as np
import matplotlib.pyplot as plt
x,y=np.meshgrid(np.linspace(-8,8),np.linspace(-8,8))
r = np.sqrt(x**2 + y**2)
z = np.sin(r)/r
fig = plt.figure()
ax = fig.add_subplot(projection='3d')
ax.plot_surface(x,y,z,cmap='Spectral_r',alpha=0.9)
ax.contourf(x,y,z,lw=2,colors='black',offset=-1)
ax.contourf(x,y,z,cmap='Spectral_r',offset=-1,alpha=0.75)
ax.set(zlim = (-1, 0.8))

import numpy as np
import matplotlib.pyplot as plt
np.random.seed(2)
data = np.random.random((8,8))
fig,ax = plt.subplots()
ax.imshow(data,cmap="Blues")